name: Git Actions CI/CD
on:
  push:
    branches:
      - main
      - dev
  
  pull_request:
    branches:
      - main
      - dev 


jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
      - name: Git Clone
        uses: actions/checkout@v2
      - name: Read hello.txt
        run: cat hello.txt

